//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutozapBDEntities : DbContext
    {
        private static AutozapBDEntities _context;
        public AutozapBDEntities()
            : base("name=AutozapBDEntities")
        {
        }
    public static AutozapBDEntities GetContext()
        {
            if (_context == null)
                _context = new AutozapBDEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<CorzinaSet> CorzinaSet { get; set; }
        public virtual DbSet<OrderSet> OrderSet { get; set; }
        public virtual DbSet<TovariSet> TovariSet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<Zap> Zap { get; set; }
       
    }
}
