//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovariSet
    {
        public int Id_tov { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Category { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Corzina_Id_cor { get; set; }
    
        public virtual CorzinaSet CorzinaSet { get; set; }
        public virtual OrderSet OrderSet { get; set; }
    }
}
